<?php

namespace AppBundle\Repository;

/**
 * SamochodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamochodRepository extends \Doctrine\ORM\EntityRepository
{
}
