<?php

namespace AppBundle\Repository;

/**
 * ZamowienieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZamowienieRepository extends \Doctrine\ORM\EntityRepository
{
}
